### ISSUE TITLE
scala.tools.nsc.MissingRequirementError: object scala not found.

### ISSUE THREAD

**Issue by roddet** [nhuray/gatling-maven-project#4]
I have clone project and execute : <code>mvn gatling:execute</code>

But the project doesn't compile : scala.tools.nsc.MissingRequirementError: object scala not found.

Any idea ?

Complete log :

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building gatling-maven-project 1.1.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gatling-maven-plugin:1.1.2:execute (default-cli) @ gatling-maven-project ---
[INFO] Collecting simulations...
[INFO] Exception in thread "main" scala.tools.nsc.MissingRequirementError: object scala not found.
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModuleOrClass(Definitions.scala:655)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModule(Definitions.scala:605)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackage(Definitions.scala:145)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackageClass(Definitions.scala:146)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.AnyClass(Definitions.scala:176)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:814)
[INFO]  at scala.tools.nsc.Global$Run.<init>(Global.scala:697)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$$anonfun$compile$1.apply(Gatling.scala:171)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$$anonfun$compile$1.apply(Gatling.scala:166)
[INFO]  at com.excilys.ebi.gatling.core.util.IOHelper$.use(IOHelper.scala:24)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.compile(Gatling.scala:166)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.start(Gatling.scala:110)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$.main(Gatling.scala:73)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.main(Gatling.scala)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.322s
[INFO] Finished at: Sat May 19 02:38:06 CEST 2012
[INFO] Final Memory: 4M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.excilys.ebi.gatling:gatling-maven-plugin:1.1.2:execute (default-cli) on project gatling-maven-project: Gatling failed. Java returned: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by slandelle** [comment]
Hi,

I just tested, and I works perfectly fine for me.
Which version of maven do you use?
Could you happen to be forced through an entreprise repository that won't let you download scala?

Cheers,

Stephane

**Comment by slandelle** [comment]
Also, which version of java do you use?

**Comment by slandelle** [comment]
@roddet The project still uses Gatling 1.1.2. There's been a few issues on gatling-maven-plugin on Windows that's been fixed since. Could you upgrade, please?
@nhuray I'v sen a pull request for upgrading.

Cheers,

Steph

**Comment by roddet** [comment]
Thanks for replies.

I'm on Mac OS X Lion.

My local config (maven, java, OS) :
Apache Maven 3.0.3 (r1075438; 2011-02-28 18:31:09+0100)
Maven home: /usr/share/maven
Java version: 1.6.0_31, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.7.3", arch: "x86_64", family: "mac"

I clean my local repository, the directories org.scala-tools, com.excilys, net.alchim31 to force re-downloading.
I've the same error scala.tools.nsc.MissingRequirementError: object scala not found.

I've upgrade gatling version to 1.1.6 (the last I think).
I've the same error.

In other scala project, I've the same error when i add a "com.excilys.ebi.gatling:gatling-app" dependency in the project. Without it compile perfectly.

Any idea ?

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building gatling-maven-project 1.1.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gatling-maven-plugin:1.1.6:execute (default-cli) @ gatling-maven-project ---
[INFO] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[INFO] SLF4J: Defaulting to no-operation (NOP) logger implementation
[INFO] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Collecting simulations...
[INFO] Exception in thread "main" scala.tools.nsc.MissingRequirementError: object scala not found.
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModuleOrClass(Definitions.scala:655)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.getModule(Definitions.scala:605)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackage(Definitions.scala:145)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.ScalaPackageClass(Definitions.scala:146)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.AnyClass(Definitions.scala:176)
[INFO]  at scala.tools.nsc.symtab.Definitions$definitions$.init(Definitions.scala:814)
[INFO]  at scala.tools.nsc.Global$Run.<init>(Global.scala:697)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$$anonfun$compile$1.apply(Gatling.scala:167)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$$anonfun$compile$1.apply(Gatling.scala:162)
[INFO]  at com.excilys.ebi.gatling.core.util.IOHelper$.use(IOHelper.scala:24)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.compile(Gatling.scala:162)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.start(Gatling.scala:106)
[INFO]  at com.excilys.ebi.gatling.app.Gatling$.main(Gatling.scala:72)
[INFO]  at com.excilys.ebi.gatling.app.Gatling.main(Gatling.scala)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.998s
[INFO] Finished at: Sat May 19 13:10:02 CEST 2012
[INFO] Final Memory: 4M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.excilys.ebi.gatling:gatling-maven-plugin:1.1.6:execute (default-cli) on project gatling-maven-project: Gatling failed. Java returned: 1 -> [Help 1]

**Comment by roddet** [comment]
It works fine on my Windows env :
- maven 3.0.3
- java 1.6.0_29
- windows 7

I've this problem only on my mac env.

**Comment by slandelle** [comment]
Very strange, as I run on Mac OS X Lion too, and don't have any problem.
Maybe you have a blank in your gatling path:
https://github.com/excilys/gatling/wiki/Getting-Started#wiki-install

**Comment by roddet** [comment]
I remove all my local maven repository and after that, it works fine.
My local repository contained probably a corrupt JAR.

Thanks for help.

**Comment by slandelle** [comment]
Glad to hear.

Have fun!
